version: "3.8"
services:
  testpoint:
    build:
        context: .
        dockerfile: Dockerfile
    #image: perfsonar/testpoint:4.4.0-systemd
    environment: 
      - container=docker
      - TZ=UTC
    network_mode: "host"
    restart: on-failure
    #privileged: true
    tmpfs: 
      - /run
      - /tmp:exec
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tty: true
